.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DB_BACKUP\.RB" "1" "June 2012" "" ""
.
.SH "NAME"
\fBdb_backup\.rb\fR \- backup one or more MySQL databases
.
.SH "SYNOPSIS"
.
.nf

`db_backup\.rb` <database_name><br>
`db_backup\.rb` `\-u username` `\-p password` <database_name><br>
`db_backup\.rb` `\-i`|`\-\-iteration` <database_name>
.
.fi
.
.SH "DESCRIPTION"
.
.nf

**db_backup\.rb** is a simple command\-line tool for backing up a
MySQL database\.  It does so safely and quietly, using a sensible
name for the backup files, so it\'s perfect for use with cron as
a daily backup\.
.
.fi

